---

- hosts: 127.0.0.1
  #become: true

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    srv1_pas:
    srv1_ip:
    srv2_pas:
    srv2_ip:
    srv3_pas:
    srv3_ip:

  vars_prompt:

    - name: srv_numbers
      private: False
      prompt: "Enter the number of servers"

  tasks:

  - name: srv1 ip
    pause:
      prompt: "Enter IP address of the server №1"
    register: ip1
    when: srv_numbers|int >= 1
  - name: srv1 pas
    pause:
      prompt: "Enter the password from the server №1"
    register: pas1
    when: srv_numbers|int >= 1
  - name: srv1
    set_fact:
     srv1_ip: "{{ ip1.user_input }}"
     srv1_pas: "{{ pas1.user_input }}"
    when: srv_numbers|int >= 1

  - name: srv2 ip
    pause:
      prompt: "Enter IP address of the server №2"
    register: ip2
    when: srv_numbers|int >= 2
  - name: srv2 pas
    pause:
      prompt: "Enter the password from the server №2"
    register: pas2
    when: srv_numbers|int >= 2
  - name: srv2
    set_fact:
     srv2_ip: "{{ ip2.user_input }}"
     srv2_pas: "{{ pas2.user_input }}"
    when: srv_numbers|int >= 2

  - name: srv3 ip
    pause:
      prompt: "Enter IP address of the server №3"
    register: ip3
    when: srv_numbers|int >= 3
  - name: srv3 pas
    pause:
      prompt: "Enter the password from the server №3"
    register: pas3
    when: srv_numbers|int >= 3
  - name: srv3
    set_fact:
     srv3_ip: "{{ ip3.user_input }}"
     srv3_pas: "{{ pas3.user_input }}"
    when: srv_numbers|int >= 3

#  - name: Add the WireGuard PPA
#    apt_repository:
#      repo: 'ppa:wireguard/wireguard'

  - name: Install WireGuard and other requirements 
    apt: name=wireguard  state=present update_cache=true

  - name: Generate private and public keys for the client and server
    shell: umask 077; wg genkey | tee {{ item.private }} | wg pubkey > {{ item.public }}
    loop:
      - { private: client1_private_key, public: client1_public_key }
      - { private: client2_private_key, public: client2_public_key }
      - { private: client3_private_key, public: client3_public_key }
      - { private: client4_private_key, public: client4_public_key }
      - { private: client5_private_key, public: client5_public_key }
      - { private: client6_private_key, public: client6_public_key }
      - { private: client7_private_key, public: client7_public_key }
      - { private: client8_private_key, public: client8_public_key }
      - { private: client9_private_key, public: client9_public_key }                         
      - { private: server_1_private_key, public: server_1_public_key }
      - { private: server_2_private_key, public: server_2_public_key }
      - { private: server_3_private_key, public: server_3_public_key }

  - name: Register the key file contents
    command: cat {{ item }}
    register: key_files
    loop:
      - client1_private_key
      - client1_public_key
      - client2_private_key
      - client2_public_key
      - client3_private_key
      - client3_public_key
      - client4_private_key
      - client4_public_key 
      - client5_private_key
      - client5_public_key
      - client6_private_key
      - client6_public_key
      - client7_private_key
      - client7_public_key
      - client8_private_key
      - client8_public_key 
      - client9_private_key
      - client9_public_key                      
      - server_1_private_key
      - server_1_public_key
      - server_2_private_key
      - server_2_public_key
      - server_3_private_key
      - server_3_public_key

  - name: Assign the keys to their variables
    set_fact:
      client1_private_key: "{{ key_files.results[0].stdout }}"
      client1_public_key: "{{ key_files.results[1].stdout }}"
      client2_private_key: "{{ key_files.results[2].stdout }}"
      client2_public_key: "{{ key_files.results[3].stdout }}"
      client3_private_key: "{{ key_files.results[4].stdout }}"
      client3_public_key: "{{ key_files.results[5].stdout }}"
      client4_private_key: "{{ key_files.results[6].stdout }}"
      client4_public_key: "{{ key_files.results[7].stdout }}"
      client5_private_key: "{{ key_files.results[8].stdout }}"
      client5_public_key: "{{ key_files.results[9].stdout }}"
      client6_private_key: "{{ key_files.results[10].stdout }}"
      client6_public_key: "{{ key_files.results[11].stdout }}"
      client7_private_key: "{{ key_files.results[12].stdout }}"
      client7_public_key: "{{ key_files.results[13].stdout }}"
      client8_private_key: "{{ key_files.results[14].stdout }}"
      client8_public_key: "{{ key_files.results[15].stdout }}"
      client9_private_key: "{{ key_files.results[16].stdout }}"
      client9_public_key: "{{ key_files.results[17].stdout }}"                                                           
      server_1_private_key: "{{ key_files.results[18].stdout }}"
      server_1_public_key: "{{ key_files.results[19].stdout }}"
      server_2_private_key: "{{ key_files.results[20].stdout }}"
      server_2_public_key: "{{ key_files.results[21].stdout }}"
      server_3_private_key: "{{ key_files.results[22].stdout }}"
      server_3_public_key: "{{ key_files.results[23].stdout }}"

  - name: Vars
    template:
      src: "templates/vars.yml"
      dest: "/root/doublevpn/vars.yml"

  - name: Generate client config
    template:
      src: "templates/wg-client.conf"
      dest: "/root/doublevpn/wg-client.conf"
      owner: root
      group: root
      mode: 0600



